CREATE DATABASE BTL_ASPNetCore
GO
USE BTL_ASPNetCore

select * from Accounts

CREATE TABLE Roles(
	RoleID INT IDENTITY PRIMARY KEY,
	NameRole NVARCHAR(250) UNIQUE NOT NULL,
	Status BIT DEFAULT(1) NOT NULL
)

select Products.* ,Categories.CategoryID, Categories.ParentID from Products INNER JOIN Categories On Products.CategoryID = Categories.CategoryID where ParentID = 'C333'

INSERT INTO Roles VALUES(N'Quản Trị',1)
INSERT INTO Roles VALUES(N'Khách Hàng',1)

CREATE TABLE Accounts(
	AccountID INT IDENTITY PRIMARY KEY,
	UserName NVARCHAR(250) NOT NULL,
	Email NVARCHAR(250) UNIQUE NOT NULL,
	Password NVARCHAR(250) NOT NULL,
	Status BIT DEFAULT(1) NOT NULL,
	RoleID INT FOREIGN KEY REFERENCES Roles(RoleID)
)

INSERT INTO Accounts VALUES('Admin','admin123@gmail.com','12345',1,1);

CREATE TABLE Categories(
	CategoryID NVARCHAR(250) PRIMARY KEY,
	NameCategory NVARCHAR(250) UNIQUE NOT NULL,
	Status BIT DEFAULT(1) NOT NULL,
	ParentID NVARCHAR(250) DEFAULT '0'
)

CREATE TABLE Materials(
	MaterialID NVARCHAR(250) PRIMARY KEY,
	NameMaterial NVARCHAR(250) UNIQUE NOT NULL,
	Status BIT DEFAULT(1) NOT NULL
)

CREATE TABLE Brands(
	BrandID NVARCHAR(250) PRIMARY KEY,
	NameBrand NVARCHAR(250) UNIQUE NOT NULL,
	Image NVARCHAR(250) NOT NULL,
	Status BIT DEFAULT(1) NOT NULL
)

CREATE TABLE Colors(
	ColorID NVARCHAR(250) PRIMARY KEY,
	NameColor NVARCHAR(250) NOT NULL,
	Status BIT DEFAULT(1) NOT NULL
)

select * from Products order by Created_at asc
CREATE TABLE Products(
	ProductID NVARCHAR(250) PRIMARY KEY,
	NameProduct NVARCHAR(250) UNIQUE,
	Image NVARCHAR(250) NOT NULL,
	Price FLOAT NOT NULL,
	SalePrice FLOAT DEFAULT(0) NOT NULL,
	Description NTEXT,
	Quantity INT NOT NULL,
	Status BIT DEFAULT(1) NOT NULL,
	Created_at DATE DEFAULT GETDATE(),
	CategoryID NVARCHAR(250) FOREIGN KEY REFERENCES Categories(CategoryID),
	MaterialID NVARCHAR(250) FOREIGN KEY REFERENCES Materials(MaterialID),
	BrandID NVARCHAR(250) FOREIGN KEY REFERENCES Brands(BrandID)
)

CREATE TABLE Orders(
	OrderID INT IDENTITY PRIMARY KEY,
	Email NVARCHAR(250) NOT NULL,
	NameCustomer NVARCHAR(250) NOT NULL,
	Phone NVARCHAR(250) NOT NULL,
	TotalQuantity INT NOT NULL,
	TotalMoney FLOAT NOT NULL,
	Adress NTEXT NOT NULL,
	Note NTEXT NOT NULL,
	Created_at DATE DEFAULT GETDATE(),
	Status INT DEFAULT(1) NOT NULL
)

CREATE TABLE OrderDetails(
	OrderDetailsID INT IDENTITY PRIMARY KEY,
	OrderID INT FOREIGN KEY REFERENCES Orders(OrderID),
	ProductID NVARCHAR(250) FOREIGN KEY REFERENCES Products(ProductID),
	Price FLOAT NOT NULL,
	Quantity INT NOT NULL,
	Color NVARCHAR(250) NOT NULL
)

CREATE TABLE ProductColors(
	ProductColorsID INT IDENTITY PRIMARY KEY,
	ColorID NVARCHAR(250) FOREIGN KEY REFERENCES Colors(ColorID),
	ProductID NVARCHAR(250) FOREIGN KEY REFERENCES Products(ProductID)
)

CREATE TABLE RelatedImage(
	RelatedImageID INT IDENTITY PRIMARY KEY,
	Image NVARCHAR(250) NOT NULL,
	ProductID NVARCHAR(250) FOREIGN KEY REFERENCES Products(ProductID)
)

CREATE TABLE WishLists(
	WishListsID INT IDENTITY PRIMARY KEY,
	AccountID INT FOREIGN KEY REFERENCES Accounts(AccountID),
	ProductID NVARCHAR(250) FOREIGN KEY REFERENCES Products(ProductID)
)

select * from WishLists
drop table WishLists

CREATE TABLE Posts(
	PostID INT IDENTITY PRIMARY KEY,
	NamePost NVARCHAR(250) NOT NULL,
	Content NTEXT NOT NULL,
	Status BIT DEFAULT(1) NOT NULL
)

drop database BTL_ASPNetCore
